<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>ZAssistant</AssemblyName>
        <RootNamespace>ZAssistant</RootNamespace>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <UseXeto>True</UseXeto>

        <Configurations>Debug;Release</Configurations>
        <Platforms>AnyCPU</Platforms>
        <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>

        <TargetFramework>net8.0-windows</TargetFramework>
        <OutputType>WinExe</OutputType>
        <StartupObject>ZAssistant.Program</StartupObject>
        <PlatformTarget>x64</PlatformTarget>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <OutputPath>..\bin\</OutputPath>
    </PropertyGroup>

    <Import Project="..\GKConfigurations3.targets" />


    <ItemGroup>
        <Reference Include="BSLib">
            <HintPath>..\libs\BSLib.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ZLMKit\ZLMKit.csproj" />
        <ProjectReference Include="..\ZLMTools\ZLMTools.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Eto.Forms" Version="2.10.0" />
        <PackageReference Include="Eto.Serialization.Xaml" Version="2.10.0" />
        <PackageReference Include="Eto.Platform.Wpf" Version="2.10.0" />
        <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4022.49" />

        <PackageReference Include="SmartComponents.LocalEmbeddings" Version="0.1.0-preview10148" PrivateAssets="All" />
        <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
        <PackageReference Include="Markdig" Version="1.3.2" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="Properties\AssemblyInfo.cs" />
        <Compile Include="Forms\UIHelper.cs" />
        <Compile Include="Forms\GKInputBox.cs" />
        <Compile Include="Utilities\AppSettings.cs" />
        <Compile Include="Utilities\ILangMan.cs" />
        <Compile Include="Utilities\LangMan.cs" />
        <Compile Include="Forms\LMChatForm.cs" />
        <Compile Include="Utilities\LSID.cs" />
        <Compile Include="Program.cs" />
        <Compile Include="Utilities\ZARuntimeContext.cs" />
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="ZAssistant.enu">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="ZAssistant.rus">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
